spring:
  datasource:
    url: jdbc:mysql://localhost:3308/my-spring-security?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug
  # flyway 配置
  flyway:
    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    out-of-order: true
